SYSTEM_PROMPT = """You are a smart and intelligent Named Entity Recognition (NER) system on tax documents. I will provide you the text from where you need \
to extract the entities.
If any of the entity doesn't exist, return `null` for that entity. Additionally, determine whether the current page is an instruction page or not.

The page should be classified as an instruction page only if it predominantly contains instructional content, such as:
- Dense text without form fields/entities
- Usage of bullet points or numbered lists
- Headers or titles or subtitles like "Instructions" or "General Information" etc.
- A lack of specific form fields/entities

However, if the page contains both form fields/entities and instructional content, it should NOT be classified as an instruction page.
"""

USER_PROMPT = """### **Extract entities from the following markdown :** \n\n📝 **Markdown:** """

SYSTEM_PROMPT_VOUCHER66 = "the transmittal content: " + \
"December 8, 2022\r\nJack & Jill Anderson\r\n1234 Main Street\r\nNewport Beach, CA 92660\r\nDear Mr. and Mrs. Anderson:\r\nEnclosed are your 2022 income tax return and 2023 estimated\r\ntax vouchers.\r\nSpecific filing instructions are as follows.\r\nFEDERAL INCOME TAX RETURN:\r\nThis return has qualified for electronic filing and the\r\npractitioner PIN program has been elected. After reviewing\r\nthe return for completeness and accuracy, please sign and\r\nreturn Form 8879 to our office. We will then transmit your\r\nreturn electronically to the IRS, and no further action is\r\nrequired.\r\nYour check for $502528, payable to the United States\r\nTreasury, must be paid by April 18, 2023. Be sure to include\r\nyour payment with Form 1040-V, Form 1040 Payment Voucher.\r\nInclude your social security number, daytime phone number,\r\nand the words \"2022 Form 1040\" on your check.\r\nMail to - Internal Revenue Service Center\r\nP.O. Box 802501\r\nCincinnati, OH 45280-2501\r\nYour income tax return includes a penalty for underpayment of\r\nestimated tax from Form 2210 of $17464.\r\nFEDERAL ESTIMATED TAX VOUCHERS:\r\nSeparately mail voucher 1 of Form 1040-ES by April 18, 2023.\r\nMail to - Internal Revenue Service Center\r\nP.O. Box 802502\r\nCincinnati, OH 45280-2502\r\nEnclose your check for $140000, payable to the United States\r\nTreasury. Include your social security number and the words\r\n\"2023 Form 1040-ES\" on your check.\r\nRetain vouchers 2, 3 and 4 in your files and mail to the\r\nabove address on or before the dates indicated.\r\nFor your reference we have listed all estimated tax payments\r\nand their original due dates below. Vouchers requiring no\r\npayment should not be filed.\r\nVoucher no. 1 by 04/18/23 ....... $140000\r\nVoucher no. 2 by 06/15/23 ....... $140000\r\nVoucher no. 3 by 09/15/23 ....... $140000\r\nVoucher no. 4 by 01/16/24 ....... $140000\r\nYour copy of the return is enclosed for your files. We\r\nsuggest that you retain this copy indefinitely.\r\nVery truly yours,\r\nCaroline Lynn\r\n"+ \
    " give the result as: " + \
"{\r\n  \"vouchers\": [\r\n    {\r\n\t  \"authority\": \"Federal\",\r\n      \"paymentAmount\": 502528,\r\n      \"dueDate\": \"04/18/23\",\r\n      \"voucherType\": \"PaymentVoucher\"\r\n\t},\r\n    {\r\n      \"authority\": \"Federal\",\r\n      \"paymentAmount\": 140000,\r\n      \"dueDate\": \"04/18/23\",\r\n      \"voucherType\": \"EstimatedVoucher\"\r\n    },\r\n    {\r\n      \"authority\": \"Federal\",\r\n      \"paymentAmount\": 140000,\r\n      \"dueDate\": \"06/15/23\",\r\n      \"voucherType\": \"EstimatedVoucher\"\r\n    },\r\n    {\r\n      \"authority\": \"Federal\",\r\n      \"paymentAmount\": 140000,\r\n      \"dueDate\": \"09/15/23\",\r\n      \"voucherType\": \"EstimatedVoucher\"\r\n    },\r\n    {\r\n      \"authority\": \"Federal\",\r\n      \"paymentAmount\": 140000,\r\n      \"dueDate\": \"01/16/24\",\r\n      \"voucherType\": \"EstimatedVoucher\"\r\n    }\r\n  ]\r\n}" + \
" the transmittal content:" + \
"December 8, 2022\r\nJack & Jill Anderson\r\n1234 Main Street\r\nNewport Beach, CA 92660\r\nDear Mr. and Mrs. Anderson:\r\nEnclosed are your 2022 Alabama Income Tax return and 2023\r\nestimated tax vouchers.\r\nThis return has qualified for electronic filing. After you\r\nhave reviewed your return for completeness and accuracy,\r\nplease sign, date and return Form AL8453 to our office. We\r\nwill then transmit your return electronically to the ADOR,\r\nand no further action is required. Do not mail the paper\r\ncopy of the return to the ADOR.\r\nYour check for $49204, payable to Alabama Department of\r\nRevenue, must be mailed by April 18, 2023. Be sure to attach\r\nyour payment to Alabama Form AL 40V, Payment Voucher.\r\nInclude your social security number, daytime phone number and\r\nthe words \"2022 Form 40\" on your check.\r\nMail to - Alabama Department of Revenue\r\nP.O. Box 327467\r\nMontgomery, AL 36132-7467\r\nYour Alabama return includes a penalty for underpayment of\r\nestimated tax of $1712.\r\nALABAMA ESTIMATED TAX VOUCHERS:\r\nSeparately mail voucher 1 of the declaration of estimated tax\r\nby April 18, 2023. Enclose your check for $13061, payable to\r\nAlabama Department of Revenue. Include your social security\r\nnumber and daytime phone number on your check.\r\nAdditional estimated tax payments will also be due. Payments\r\nshould be mailed to the following address on or before the\r\ndates indicated.\r\nMail to - Alabama Department of Revenue\r\nIndividual Estimates\r\nP.O. Box 327485\r\nMontgomery, AL 36132-7485\r\nFor your reference we have listed all estimated tax payments\r\nand their original due dates below.\r\nVoucher no. 1 by 04/18/23 ....... $13061\r\nVoucher no. 2 by 06/15/23 ....... $13061\r\nVoucher no. 3 by 09/15/23 ....... $13061\r\nVoucher no. 4 by 01/16/24 ....... $13061\r\nYour copy of the return is enclosed for your files. We\r\nsuggest that you retain this copy indefinitely.\r\nVery truly yours,\r\nCaroline Lynn\r\n" + \
" give the result as: " + \
"{\r\n  \"vouchers\": [\r\n    {\r\n\t  \"authority\": \"Alabama\",\r\n      \"paymentAmount\": 49204,\r\n      \"dueDate\": \"04/18/23\",\r\n      \"voucherType\": \"PaymentVoucher\"\r\n\t},\r\n    {\r\n      \"authority\": \"Alabama\",\r\n      \"paymentAmount\": 13061,\r\n      \"dueDate\": \"04/18/23\",\r\n      \"voucherType\": \"EstimatedVoucher\"\r\n    },\r\n    {\r\n      \"authority\": \"Alabama\",\r\n      \"paymentAmount\": 13061,\r\n      \"dueDate\": \"06/15/23\",\r\n      \"voucherType\": \"EstimatedVoucher\"\r\n    },\r\n    {\r\n      \"authority\": \"Alabama\",\r\n      \"paymentAmount\": 13061,\r\n      \"dueDate\": \"09/15/23\",\r\n      \"voucherType\": \"EstimatedVoucher\"\r\n    },\r\n    {\r\n      \"authority\": \"Alabama\",\r\n      \"paymentAmount\": 13061,\r\n      \"dueDate\": \"01/16/24\",\r\n      \"voucherType\": \"EstimatedVoucher\"\r\n    }\r\n  ]\r\n}" + \
    "the transmittal content: " + \
"Filing Instructions\r\nJack & Jill Anderson Hatfield & Associates\r\n1234 Main Street 8186 Jackson Rd., Suite 100\r\nNewport Beach, CA 92660 Ann Arbor, MI 48103\r\nREPORT OF FOREIGN BANK AND FINANCIAL ACCOUNTS - JOINT\r\nYour Form 114 has been prepared for electronic filing. Please sign,\r\ndate, and return Form 114A to our office. We will then transmit your\r\nform to the FINCEN.\r\n2022 ALABAMA INCOME TAX RETURN\r\nYou have a balance due of..........................$ 49204\r\n2023 ALABAMA ESTIMATED INCOME TAX\r\nEstimated tax vouchers are due as follows:\r\n$ 13061 due by April 18, 2023\r\n$ 13061 due by June 15, 2023\r\n$ 13061 due by September 15, 2023\r\n$ 13061 due by January 16, 2024\r\nInclude your SSN and phone number on your check.\r\nMail on or before the due date to: Alabama Department of Revenue\r\nIndividual Estimates\r\nP.O. Box 327485\r\nMontgomery, AL 36132-7485\r\n200061\r\n04-01-22\r\nPrepared for: Prepared by:\r\nFiling Instructions\r\nJack & Jill Anderson Hatfield & Associates\r\n1234 Main Street 8186 Jackson Rd., Suite 100\r\nNewport Beach, CA 92660 Ann Arbor, MI 48103\r\n2022 ALABAMA ELECTRONIC FILING INFORMATION\r\nThis return has qualified for electronic filing. After you have\r\nreviewed your return for completeness and accuracy, please sign, date\r\nand return Form AL8453 to our office. We will then submit your\r\nelectronic return to the ADOR. Do not mail the paper copy of the return\r\nto the ADOR.\r\nPayment should be submitted with Alabama Form AL 40V. Include your\r\nsocial security number, phone number and the words \"2022 Form 40\" on\r\nyour check. Make your check for $49204 payable to Alabama Department of\r\nRevenue. Be sure to attach your payment to Alabama Form AL 40V, Payment\r\nVoucher.\r\nMail by April 18, 2023 to: Alabama Department of Revenue\r\nP.O. Box 327467\r\nMontgomery, AL 36132-7467\r\n" + \
    "give the result as: " + \
"{\r\n  \"vouchers\": [\r\n    {\r\n\t  \"authority\": \"Alabama\",\r\n      \"paymentAmount\": 49204,\r\n      \"dueDate\": \"04/18/23\",\r\n      \"voucherType\": \"PaymentVoucher\"\r\n\t},\r\n    {\r\n      \"authority\": \"Alabama\",\r\n      \"paymentAmount\": 13061,\r\n      \"dueDate\": \"04/18/23\",\r\n      \"voucherType\": \"EstimatedVoucher\"\r\n    },\r\n    {\r\n      \"authority\": \"Alabama\",\r\n      \"paymentAmount\": 13061,\r\n      \"dueDate\": \"06/15/23\",\r\n      \"voucherType\": \"EstimatedVoucher\"\r\n    },\r\n    {\r\n      \"authority\": \"Alabama\",\r\n      \"paymentAmount\": 13061,\r\n      \"dueDate\": \"09/15/23\",\r\n      \"voucherType\": \"EstimatedVoucher\"\r\n    },\r\n    {\r\n      \"authority\": \"Alabama\",\r\n      \"paymentAmount\": 13061,\r\n      \"dueDate\": \"01/16/24\",\r\n      \"voucherType\": \"EstimatedVoucher\"\r\n    }\r\n  ]\r\n}" + \
    "the transmittal content: " + \
"2022 TAX RETURN FILING INSTRUCTIONS\\r\\nU.S. INDIVIDUAL INCOME TAX RETURN\\r\\n\\r\\nFOR THE YEAR ENDING\\r\\nDecember 31, 2022\\r\\n\\r\\nPrepared For:\\r\\n\\r\\nJonathan D. \\r\\n6820 West 321th St Apt. No. 61B\\r\\nNew York, NY 10025\\r\\n\\r\\nPrepared By:\\r\\n\\r\\nHolland LLP\\r\\n1235 Research Boulevard #600\\r\\nRockville, MD 20850\\r\\n\\r\\nAmount of Tax:\\r\\n\\r\\nTotal tax $ 7,123\\r\\nLess: payments and credits $ 6,808\\r\\nPlus: interest and penalties $ 11\\r\\nBalance due $ 326\\r\\n\\r\\nOverpayment:\\r\\n\\r\\nNot applicable\\r\\n\\r\\nMake Check Payable To:\\r\\n\\r\\nNot applicable\\r\\n\\r\\nMail Tax Return and Check (if applicable) To:\\r\\n\\r\\nThis return has qualified for electronic filing and the practitioner PIN program has been elected. We have transmitted your return electronically to the IRS, and no further action is required.\\r\\n\\r\\nReturn Must Be Mailed On Or Before:\\r\\n\\r\\nReturn federal Form 8879 to us by October 16, 2023.\\r\\n\\r\\nSpecial Instructions:\\r\\n\\r\\nDo not mail the paper copy of the return to the IRS.\\r\\n\\r\\nYour balance due of $326 will be automatically withdrawn from your account ending in 6676 on or after October 16, 2023. Refer to Form 1040 on the Direct Deposit/Debit Report for complete account information.\\r\\n\\r\\nIf your tax return(s) are being electronically filed, we cannot release them until we have your signed authorization(s). After reviewing your return(s) for accuracy and completeness, please sign and email your authorization(s) to 8879.Rockville@marcumllp.com or fax to (301) 979-6001. Our mailing address is 1 Research Court, Suite 400 Rockville, MD 20850.\\r\\n\\r\\ngive the result as:\r\n" + \
    "give the result as: " + \
"{\r\n  \"vouchers\": [\r\n    {\r\n\t  \"authority\": \"Federal\",\r\n      \"paymentAmount\": 326.0,\r\n      \"dueDate\": \"10/16/23\",\r\n      \"voucherType\": \"PaymentVoucher\"\r\n}\r\n ]\r\n}"

USER_PROMPT_VOUCHER = "learn from the above template json output  for each transmittals to give me the json for the below similar content and please don't add ```json in response. Please extract only vouchers amount due, authority,due dates and type from below text in json format .If one state has multiple vouchers, a multiple voucher section will be required. A separate voucher json section should be used for each different due date. Do not club due dates or amounts in single voucher json section even if same.  If amount is zero please mention 0 and ignore $ symbol. Type should be refund or voucher or penalty . Date should in MM/dd/yy format. Due date can also be present like \\\"\"mailed by April 15, 2021\\\"\".Please ignore penalty and refund types. Give empty array if no vouchers found Only include voucher which need action from the user.If there are multiple actionable voucher and their sum, then ignore the sum. Find and store the voucherType based on this types : Payment (1), Estimated (2) and Unknown (0) indicating an unspecified type, store only int, please ignore ```json"


SYSTEM_PROMPT_VOUCHER_INSTALLMENT = "the transmittal content: "+ \
    "December 8, 2022\r\nJack & Jill Anderson\r\n1234 Main Street\r\nNewport Beach, CA 92660\r\nDear Mr. and Mrs. Anderson:\r\nEnclosed are your 2022 income tax return and 2023 estimated\r\ntax vouchers.\r\nSpecific filing instructions are as follows.\r\nFEDERAL INCOME TAX RETURN:\r\nThis return has qualified for electronic filing and the\r\npractitioner PIN program has been elected. After reviewing\r\nthe return for completeness and accuracy, please sign and\r\nreturn Form 8879 to our office. We will then transmit your\r\nreturn electronically to the IRS, and no further action is\r\nrequired.\r\nYour check for $502528, payable to the United States\r\nTreasury, must be paid by April 18, 2023. Be sure to include\r\nyour payment with Form 1040-V, Form 1040 Payment Voucher.\r\nInclude your social security number, daytime phone number,\r\nand the words \"2022 Form 1040\" on your check.\r\nMail to - Internal Revenue Service Center\r\nP.O. Box 802501\r\nCincinnati, OH 45280-2501\r\nYour income tax return includes a penalty for underpayment of\r\nestimated tax from Form 2210 of $17464.\r\nFEDERAL ESTIMATED TAX VOUCHERS:\r\nSeparately mail voucher 1 of Form 1040-ES by April 18, 2023.\r\nMail to - Internal Revenue Service Center\r\nP.O. Box 802502\r\nCincinnati, OH 45280-2502\r\nEnclose your check for $140000, payable to the United States\r\nTreasury. Include your social security number and the words\r\n\"2023 Form 1040-ES\" on your check.\r\nRetain vouchers 2, 3 and 4 in your files and mail to the\r\nabove address on or before the dates indicated.\r\nFor your reference we have listed all estimated tax payments\r\nand their original due dates below. Vouchers requiring no\r\npayment should not be filed.\r\nInstallment no. 1 by 04/18/23 ....... $140000\r\nInstallment no. 2 by 06/15/23 ....... $140000\r\nInstallment no. 3 by 09/15/23 ....... $140000\r\nInstallment no. 4 by 01/16/24 ....... $140000\r\nYour copy of the return is enclosed for your files. We\r\nsuggest that you retain this copy indefinitely.\r\nVery truly yours,\r\nCaroline Lynn\r\n" + \
        " give the result as: " + \
"{\r\n  \"vouchers\": [\r\n    {\r\n\t  \"authority\": \"Federal\",\r\n      \"paymentAmount\": 502528,\r\n      \"dueDate\": \"04/18/23\",\r\n      \"voucherType\": \"PaymentVoucher\"\r\n\t},\r\n    {\r\n      \"authority\": \"Federal\",\r\n      \"paymentAmount\": 140000,\r\n      \"dueDate\": \"04/18/23\",\r\n      \"voucherType\": \"EstimatedVoucher\"\r\n    },\r\n    {\r\n      \"authority\": \"Federal\",\r\n      \"paymentAmount\": 140000,\r\n      \"dueDate\": \"06/15/23\",\r\n      \"voucherType\": \"EstimatedVoucher\"\r\n    },\r\n    {\r\n      \"authority\": \"Federal\",\r\n      \"paymentAmount\": 140000,\r\n      \"dueDate\": \"09/15/23\",\r\n      \"voucherType\": \"EstimatedVoucher\"\r\n    },\r\n    {\r\n      \"authority\": \"Federal\",\r\n      \"paymentAmount\": 140000,\r\n      \"dueDate\": \"01/16/24\",\r\n      \"voucherType\": \"EstimatedVoucher\"\r\n    }\r\n  ]\r\n}" 
